"""Generate scenes/leap/objects/uv_sphere.obj — a UV-mapped unit sphere.

This exists for the same reason iris_cube.obj does: texture coordinates carried
in plain OBJ `vt` are understood by every renderer in this project, whereas each
renderer's built-in projection for a sphere PRIMITIVE is its own invention, and
they do not agree. MuJoCo cube-maps (type="cube" stamps one square onto all six
faces, so a single seam appears six times) or planar-projects (type="2d", which
smears off-axis); Panda3d's primitive (panda3d_viewer/geometry.py::make_capsule)
emits a TRANSPOSED equirectangular map, latitude along image X. Put the UVs on
the mesh and all of that goes away — both renderers just read the vt.

The mapping written here is the conventional one, matching the image that
scenes/scripts/make_softball_texture.py produces:

    vt = (phi / 2pi,  1 - theta / pi)

i.e. longitude across, latitude up. The `1 -` is the OBJ/PIL disagreement about
which end of the image v=0 means (OBJ counts from the BOTTOM, PIL's row 0 is the
TOP); it lives here rather than in the texture script so exactly one side of the
pair carries the flip.

Two details that matter for a seamless wrap:
  - the phi=2pi column of vertices is duplicated (same position as phi=0, but
    vt u=1 instead of 0), because a vertex can hold only one uv — without the
    duplicate the last quad interpolates the whole texture backwards.
  - the pole rows are degenerate quads, emitted as triangles.

Unit radius; scale per geom in the MJCF, the way env_leap_eval_cube.xml scales
iris_cube.obj to object and goal-marker sizes.

    python scenes/scripts/make_uv_sphere.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

NLON = 96   # longitude divisions -> silhouette is an NLON-gon at the equator
NLAT = 48   # latitude divisions (pole to pole)

OUT = Path(__file__).parents[1] / "leap" / "objects" / "uv_sphere.obj"
MTL = OUT.with_suffix(".mtl")


def _index(i: int, j: int) -> int:
    """1-based OBJ index of the vertex on latitude ring i, longitude column j."""
    return i * (NLON + 1) + j + 1


def make_uv_sphere() -> str:
    theta = np.pi * np.arange(NLAT + 1) / NLAT          # 0 (+z pole) .. pi
    phi = 2 * np.pi * np.arange(NLON + 1) / NLON        # 0 .. 2pi (last dupes 0)

    st, ct = np.sin(theta)[:, None], np.cos(theta)[:, None]
    x = st * np.cos(phi)[None, :]
    y = st * np.sin(phi)[None, :]
    z = np.broadcast_to(ct, x.shape)

    u = np.broadcast_to(phi[None, :] / (2 * np.pi), x.shape)
    v = np.broadcast_to(1.0 - theta[:, None] / np.pi, x.shape)

    out = [f"# UV-mapped unit sphere for softball_surface.png "
           f"({NLON}x{NLAT}); generated by scenes/scripts/make_uv_sphere.py",
           f"mtllib {MTL.name}", "o uv_sphere"]
    out += [f"v {a:.6f} {b:.6f} {c:.6f}" for a, b, c in
            zip(x.ravel(), y.ravel(), z.ravel())]
    out += [f"vt {a:.6f} {b:.6f}" for a, b in zip(u.ravel(), v.ravel())]
    # On a unit sphere the outward normal is the position itself.
    out += [f"vn {a:.6f} {b:.6f} {c:.6f}" for a, b, c in
            zip(x.ravel(), y.ravel(), z.ravel())]
    out.append("usemtl uv_sphere")
    out.append("s 1")

    def face(*ks: int) -> str:
        return "f " + " ".join(f"{k}/{k}/{k}" for k in ks)

    # Quad corner order (a, b, c, d) = (i,j) (i+1,j) (i+1,j+1) (i,j+1) puts the
    # normal outward; the pole rows drop the corner that collapses onto the pole.
    for i in range(NLAT):
        for j in range(NLON):
            a, b = _index(i, j), _index(i + 1, j)
            c, d = _index(i + 1, j + 1), _index(i, j + 1)
            if i == 0:
                out.append(face(a, b, c))
            elif i == NLAT - 1:
                out.append(face(a, b, d))
            else:
                out.append(face(a, b, c, d))

    return "\n".join(out) + "\n"


MTL_TEXT = """# Material for uv_sphere.obj — the softball skin.
newmtl uv_sphere
Ka 1.000000 1.000000 1.000000
Kd 1.000000 1.000000 1.000000
Ks 0.000000 0.000000 0.000000
d 1.000000
illum 1
map_Kd ../textures/softball_surface.png
"""


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(make_uv_sphere())
    MTL.write_text(MTL_TEXT)
    print(f"wrote {OUT}")
    print(f"wrote {MTL}")
